### ISSUE TITLE
feat: Allow leaf_delegate to transfer its delegate status

### ISSUE THREAD

**Issue by mPaella** [metaplex-foundation/mpl-bubblegum#37]
Currently the leaf_owner is the only account capable of assigning a leaf_delegate

Request: Adjust the Delegate instruction to allow for the current leaf_delegate to assign a new leaf_delegate, without the leaf_owner being required to sign

**Comment by febo** [comment]
The restriction is in place on purpose, since only the `leaf_owner` should be the one to approve a delegate given the "power" that a delegate has. This is similar to how a delegate on spl-token works. Do you have a specific use-case that requires this?

**Comment by mPaella** [comment]
To be clear, we dont want to add _another_ `leaf_delegate`, but want to allow the current delegate to transfer its delegate status to a new delegate (replacing the current delegate with a new delegate, without the owner signing, via the current delegate)

I think its reasonable to assume that because the current `leaf_delegate` already has "so much power", that the owner also trusts it enough to allow it to transfer it's delegate status to a new address.

Our specific use case is our Minting API, which allows creators/devs to mint, update, and burn NFTs and cNFTs through REST APIs. Each project has its own keypair, and we often rotate these keys for improved security.

With non-compressed NFTs, we are able to do this through the updateAuthority (including changing the updateAuthority) . However with cNFTs, it actually poses a vulnerability due to the fact that if the `leaf_delegate`'s key is leaked we have **no way** of updating the `leaf_delegate` (and often the `leaf_owner` may not even be familiar with web3, so asking them to do it is very difficult)

**Comment by kespinola** [comment]
@mPaella the updateAuthority is more analogues to the tree authority. As it stands today, there is no per leaf update authority for a cNFT. The authority of the tree is the one capable of issuing changes like adjusting creators or swapping metadata json URI. However, this is a null points since the program does not expose any update actions though in the draft I was reviewing it was the tree authority that needs to initiate the request.
