### ISSUE TITLE
createTransferInstruction not available in typescript package

### ISSUE THREAD

**Issue by mordonez-me** [metaplex-foundation/mpl-bubblegum#58]
Solana docs, videos, and all information published about transferring a compressed point to the function createTransferInstruction but is not available in the current version:

![image](https://github.com/metaplex-foundation/mpl-bubblegum/assets/2242042/c88498c1-cc52-4ac1-a19c-00abe5a971ac)

Version 3.0.0

Thanks

**Comment by mordonez-me** [comment]
For reference:

https://docs.solana.com/es/developing/guides/compressed-nfts#get-the-asset
https://www.youtube.com/watch?v=FOO5eT7K_e4
https://www.youtube.com/watch?v=83nIhnxtlW8&t=2605s
https://www.helius.dev/blog/solana-nft

**Comment by danenbm** [comment]
I'm sorry we didn't respond sooner.  The reason for this is that that function is in the js-solita library, which is a previous designed version.  Version 3.0.0 is the new Umi library.

So currently, Umi is 3.1.0 and the most recent Solita version (which has createTransferInstruction) is 0.10.0.

If you you look in the js-solita client tests at https://github.com/metaplex-foundation/mpl-bubblegum/blob/main/clients/js-solita/tests/main.test.ts you can see that function being used.
