### ISSUE TITLE
Leaf owner and Leaf delegate as inputs to mint

### ISSUE THREAD

**Issue by FallingHazard** [metaplex-foundation/mpl-bubblegum#62]
Putting them in the account array creates limitations. 
The caller needs to know who is receiving the cNFT. 

Having them as inputs let's a contract at runtime decide who to give a cNFT to  ( via cpi ) based on contract state.

**Comment by FallingHazard** [comment]
Happy to work on a PR if the idea is viewed positively.

**Comment by danenbm** [comment]
Thank you for this idea and sorry for the much delayed response.  When I look at the contract I don't see any technical blocker for your suggestion.   However, making them params you would lose out on LUTs.  Given that this comment is pretty old, I'm assuming you've worked around it, and given that the `mintV1` and `mintToCollectionV1` are pretty established, if you are still interested in this change, it might be best for us to use the MIP process so we can discuss it with a bit wider audience: https://mip.metaplex.com/
