### ISSUE TITLE
Is it possible to change the treeCreator (from a Merkle Tree config account)?

### ISSUE THREAD

**Issue by vitchor** [metaplex-foundation/mpl-bubblegum#91]
Howdy! I'd like to change the `treeCreator` because I'm creating a tree from an – unsafe – account and want to completely remove authority (over the tree) from that account later on. To do that, I believe I'll need to change the TreeCreator, correct? Thanks! :)

**Comment by danenbm** [comment]
Hello, unfortunately we do not allow changing the tree authority.  We do have the tree delegate, which you can use to assign to someone else to have authority over the tree, and then can be revoked later (by setting tree delegate back to tree owner).  Please feel free to reopen this if that does not owrk for your use case.
