### ISSUE TITLE
upgrade @metaplex-foundation/mpl-token-metadata 3.0.0-alpha.27

### ISSUE THREAD

**Issue by puderty** [metaplex-foundation/mpl-bubblegum#94]
Hi, it still depends on @metaplex-foundation/mpl-token-metadata 3.0.0-alpha.27, can you upgrade to 3.2.1?

**Comment by danenbm** [comment]
yes will do this week

**Comment by danenbm** [comment]
Updated in https://github.com/metaplex-foundation/mpl-bubblegum/pull/108

**Comment by danenbm** [comment]
Deployed js client v4.2.1
